# Generated by Django 4.2.2 on 2023-06-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_network", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
    ]
