# Generated by Django 4.2.2 on 2023-06-26 15:42

from django.db import migrations
from django.core.management import call_command


def load_func(apps, schema_editor):
    call_command("loaddata", "data_to_load.json")


def to_unload_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "user",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.RunPython(load_func, to_unload_func),
    ]
