# Generated by Django 4.2.2 on 2023-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="biography"),
        ),
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures",
                verbose_name="profile picture",
            ),
        ),
    ]
