# Generated by Django 4.2.2 on 2023-10-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_auto_20230626_1842"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_request",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
