# Generated by Django 4.2.2 on 2023-06-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="username"
            ),
        ),
    ]
