# Generated by Django 4.2.2 on 2023-06-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                default="noname",
                upload_to="profile_pictures",
                verbose_name="profile picture",
            ),
            preserve_default=False,
        ),
    ]
