# Generated by Django 4.2.2 on 2023-06-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_user_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="noname", max_length=150, unique=True, verbose_name="username"
            ),
            preserve_default=False,
        ),
    ]
